### ISSUE TITLE
Seed databases with more restaurants and menu items

### ISSUE THREAD

**Issue by mattmotto** [numenu-app/numenu#44]
Focus on restaurants in the Columbia area
Restaurants should have:
Name
location
address
phone number

**Comment by mattmotto** [comment]
Menus should have all food items from the restaurant

**Comment by GeorgeDiNicola** [comment]
Seeded restaurants and associated data (8 total)
Seeded dishes and associated data (40 total)
reviews (8 total, 1 for each restaurant)
dish reviews - left as is.... Not sure how we are going to get this in a non-painful way

**Comment by GeorgeDiNicola** [comment]
Added advanced seeding functionality for tables that have foreign key associations. The logic used in seeds.rb will be extremely useful for creating new objects in the database from the application.
