### ISSUE TITLE
Add image support for restaurants and food items

### ISSUE THREAD

**Issue by mattmotto** [numenu-app/numenu#47]
My guess is the best way to store the images is in s3, but I am not sure.

**Comment by GeorgeDiNicola** [comment]
Possiblity: https://devcenter.heroku.com/articles/simple-file-upload#provisioning-the-add-on

**Comment by GeorgeDiNicola** [comment]
https://medium.com/alturasoluciones/setting-up-rails-5-active-storage-with-amazon-s3-3d158cf021ff

https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Categories=categories%23storage&trk=ps_a134p000004f2aOAAQ&trkCampaign=acq_paid_search_brand&sc_channel=PS&sc_campaign=acquisition_US&sc_publisher=Google&sc_category=Storage&sc_country=US&sc_geo=NAMER&sc_outcome=acq&sc_detail=amazon%20s3%20pricing&sc_content=S3_e&sc_matchtype=e&sc_segment=468090540619&sc_medium=ACQ-P|PS-GO|Brand|Desktop|SU|Storage|S3|US|EN|Text&s_kwcid=AL!4422!3!468090540619!e!!g!!amazon%20s3%20pricing&ef_id=CjwKCAjw6fCCBhBNEiwAem5SO5xqzENQECom9DJk29Bqpi6eu0eX7a0vI52eFcVczSW_buqmWnLWJhoCxbYQAvD_BwE:G:s&s_kwcid=AL!4422!3!468090540619!e!!g!!amazon%20s3%20pricing

**Comment by GeorgeDiNicola** [comment]
Configured in application:
- config/storage.yml
- config/environments/production.rb

Bucket name: numenu-app.herokuapp.com

Will share the AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_BUCKET env variables with the group through safe communication.
